import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const elements=new Map(),events={};
const viewport={width:1100,height:520};
const drawCalls=[];
const textCalls=[];
const ctx=new Proxy({},{get:(target,key)=>key==='createLinearGradient'?()=>({addColorStop(){}}):key==='ellipse'? (...args)=>drawCalls.push({kind:'ellipse',args}):key==='fillText'? (...args)=>textCalls.push(args):Reflect.get(target,key)||(()=>{})});
function element(id){if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',hidden:false,style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},setPointerCapture(){},addEventListener(type,fn){events[id+':'+type]=fn;},getBoundingClientRect(){return {...viewport,left:0,top:0};},focus(){},getContext(){return ctx;}});return elements.get(id);}
const sandbox={document:{getElementById:element,querySelector:()=>element('label'),addEventListener(){}},window:{devicePixelRatio:1,addEventListener(type,fn){events[type]=fn;}},Image:class{},ResizeObserver:class{observe(){}},requestAnimationFrame(){},setTimeout(){return 0;},clearTimeout(){},console};
vm.createContext(sandbox);
let source=fs.readFileSync('docs/game.js','utf8');
source=source.replace(/\}\)\(\);\s*$/,"globalThis.test={start,pause,update,eat,setMode,draw,spawnSpecial,moveSpecial,moveFish,spawn,resize,confinePlayer,screenRadius,dash,hit,spawnPickup,collectPickup,seaEvent,pressure,canEat,dangerous,inflated,clearFish:()=>{fish=[];},setElapsed:(n)=>{elapsed=n;},placePickup:(kind)=>{spawnPickup(kind);const p=pickups.at(-1);p.x=player.x;p.y=player.y;p.baseY=player.y;},placeSpecial:(type)=>{spawnSpecial(type);const f=specials.at(-1);f.x=player.x;f.y=player.y;f.baseY=player.y;f.phase=0;f.wobble=0;},get:()=>({state,score:player.score,level:player.level,lives:player.lives,elapsed,player,players,mode,fish,specials,specialClock,nextSpecial,MAX_LEVEL,species,W,H,sizeScale,pickups,shieldTime:player.shieldTime,slowTime:player.slowTime,dashTime:player.dashTime,dashCooldown:player.dashCooldown,combo:player.combo,comboTime:player.comboTime,bestCombo:player.bestCombo}),setFish:(r)=>{fish=[{x:player.x,y:player.y,baseY:player.y,r,score:1,speed:0,dir:1,phase:0,wobble:0,sprite:1}];player.invulnerable=0;}};})();");
vm.runInContext(source,sandbox);
const t=sandbox.test;
t.start();assert.equal(t.get().state,'playing');assert.equal(t.get().lives,3);
t.setFish(12);t.update(.01);assert.equal(t.get().score,1,'Eating a smaller fish increases score');
for(let i=0;i<7;i++)t.eat({score:1,x:0,y:0});assert.equal(t.get().level,0,'Eight points no longer upgrade the player');
for(let i=0;i<24;i++)t.eat({score:1,x:0,y:0});assert.equal(t.get().level,1);assert.equal(t.get().player.r,27);
t.pause();let seconds=t.get().elapsed;t.update(1);assert.equal(t.get().elapsed,seconds,'Pause freezes gameplay');t.pause();assert.equal(t.get().state,'playing');
for(let i=0;i<3;i++){t.setFish(70);t.update(.01);}assert.equal(t.get().lives,0);assert.equal(t.get().state,'over');
t.start();assert.equal(t.get().score,0);assert.equal(t.get().level,0);assert.equal(t.get().lives,3);
t.eat({score:480,x:0,y:0});assert.equal(t.get().level,5);assert.equal(t.get().state,'playing','The old level cap no longer ends the game');
t.eat({score:1420,x:0,y:0});assert.equal(t.get().level,9);assert.equal(t.get().state,'won');assert.equal(t.get().player.r,180);
t.eat({bonus:1,x:0,y:0});assert.ok(Number.isFinite(t.get().score),'Food after victory cannot produce NaN');
t.start();events.keydown({key:'ArrowLeft',preventDefault(){}});t.update(20);assert.ok(t.get().player.x>=t.get().player.r,'Movement stays inside the game area');
t.start();t.clearFish();t.placeSpecial(0);t.update(.01);assert.equal(t.get().score,21,'Jellyfish grants 65% of the first level target');assert.equal(t.get().specials.length,0);assert.ok(t.get().player.r>20,'Special food immediately grows the fish');assert.equal(t.get().lives,3);
t.start();t.clearFish();t.placeSpecial(1);t.update(.01);assert.equal(t.get().score,32);assert.equal(t.get().level,1,'Seahorse grants an entire level target');
t.start();t.clearFish();t.eat({score:100,x:0,y:0});t.placeSpecial(0);t.update(.01);assert.equal(t.get().score,160,'Bonus scales to the current level gap, not total score');
t.start();t.clearFish();t.update(24.9);assert.equal(t.get().specials.length,0);t.clearFish();t.update(.1);assert.equal(t.get().specials.length,1);assert.ok(t.get().nextSpecial>=35&&t.get().nextSpecial<=50);
t.pause();const specialX=t.get().specials[0].x,specialClock=t.get().specialClock;t.update(5);assert.equal(t.get().specials[0].x,specialX);assert.equal(t.get().specialClock,specialClock,'Pause freezes special creature movement and timers');t.pause();
t.clearFish();t.update(22);assert.equal(t.get().specials.length,0,'Uncaught special creatures leave the other edge');t.start();assert.equal(t.get().specials.length,0);assert.equal(t.get().nextSpecial,25);
t.clearFish();t.eat({score:1899,x:0,y:0});t.placeSpecial(1);t.update(.01);assert.equal(t.get().state,'won','Special food can complete level ten');
t.start();t.clearFish();
for(const type of [0,1]){t.spawnSpecial(type);const f=t.get().specials.at(-1);assert.ok(f.x<0||f.x>t.get().W,'Special creatures enter from outside the screen');f.x=80;f.baseY=100;f.dir=1;const oldX=f.x;t.moveSpecial(f,1);assert.ok(f.x-oldX>=66,'Both special species visibly swim');f.x=t.get().W-1;t.moveSpecial(f,.1);assert.ok(f.x>t.get().W);assert.equal(f.dir,1,'Special creatures continue offscreen without turning back');}
t.start();assert.equal(new Set(t.get().species.map(s=>s.name.replace(/巨型|深海巨/g,''))).size>=11,true);assert.equal(Math.max(...t.get().species.map(s=>s.r)),160);assert.equal(t.get().species.filter(s=>s.extra).map(s=>s.sprite).filter((x,i,a)=>a.indexOf(x)===i).length,6,'Six distinct new sprites are used');
t.clearFish();for(let i=0;i<48;i++)t.spawn(true);assert.ok(t.get().fish.every(f=>f.unlock===0&&f.r<=30),'Large sharks do not appear at the beginning');
t.start();t.eat({score:1010,x:0,y:0});t.clearFish();for(let i=0;i<64;i++)t.spawn(true);assert.ok(t.get().fish.filter(f=>f.r>=100).length<=3,'At most three giant sharks appear at high levels');t.setFish(160);t.update(.01);assert.equal(t.get().lives,2,'A giant shark threatens a smaller high-level player');
viewport.width=350;viewport.height=470;t.resize();t.start();t.eat({score:1890,x:0,y:0});t.get().player.x=-100;t.get().player.y=1000;t.confinePlayer();const mobile=t.get(),radius=t.screenRadius(mobile.player.r);assert.ok(mobile.player.x>=radius*1.2&&mobile.player.x<=mobile.W-radius*1.2);assert.ok(radius*2.8<=mobile.W-24,'High-level fish fit the mobile viewport');t.setFish(160);const before=t.get().score;t.update(.01);assert.equal(t.get().score,before+1,'A sufficiently grown player can eat the largest shark with scaled collisions');assert.equal(t.get().state,'playing');
console.log('PASS: ten levels, six new sprites, giant shark progression, side-to-side special swimming, bonus and pause/restart regression, mobile size and collision consistency.');
export {t,events,viewport,drawCalls,textCalls,elements};
