import assert from 'node:assert/strict';
import fs from 'node:fs';
import {t,events,viewport} from './check-game.mjs';
viewport.width=1100;viewport.height=520;t.resize();
t.eat({score:9999,x:0,y:0});t.setMode('duo');t.start();t.clearFish();
const press=key=>events.keydown({key,preventDefault(){}}),release=key=>events.keyup({key});
const pair=()=>t.get().players;
assert.equal(pair().length,2);assert.notEqual(pair()[0],pair()[1]);
let [a,b]=pair(),ax=a.x,bx=b.x,ay=a.y,by=b.y;
press('d');press('ArrowLeft');t.update(.1);release('d');release('ArrowLeft');
assert.ok(a.x>ax&&b.x<bx,'Both players move simultaneously in opposite directions');
assert.equal(a.y,ay);assert.equal(b.y,by);
ax=a.x;press('ArrowUp');t.update(.1);release('ArrowUp');assert.equal(a.x,ax);assert.equal(a.y,ay);assert.ok(b.y<by,'Arrow keys only control 2P in duo mode');
by=b.y;press('s');t.update(.1);release('s');assert.equal(b.y,by);assert.ok(a.y>ay,'WASD only controls 1P');
press('Shift');assert.equal(b.dashCooldown,6);assert.equal(a.dashCooldown,0);press(' ');assert.equal(a.dashCooldown,6);
t.eat({score:32,x:0,y:0},b);assert.equal(b.level,1);assert.equal(a.level,0);assert.equal(a.score,0);
t.eat({bonus:.65,x:0,y:0},a);assert.equal(a.score,21);assert.equal(b.score,32,'Special growth belongs to the eater');
t.collectPickup({kind:'shield',x:0,y:0},b);b.invulnerable=0;t.hit('shark',false,b);assert.equal(b.lives,3);assert.equal(b.shieldTime,0);assert.equal(a.shieldTime,0);
b.invulnerable=0;t.hit('poison',true,b);assert.equal(b.lives,2);assert.equal(b.slowTime,2);assert.equal(a.lives,3);assert.equal(a.slowTime,0);
t.collectPickup({kind:'heart',x:0,y:0},b);assert.equal(b.lives,2,'2P cannot heal');
a.dashTime=b.dashTime=0;press('d');press('ArrowLeft');const snapshot=JSON.stringify(pair());const elapsed=t.get().elapsed;t.pause();t.update(4);assert.equal(JSON.stringify(pair()),snapshot);assert.equal(t.get().elapsed,elapsed,'Pause freezes both players and all their effects');t.pause();t.clearFish();
ax=a.x;bx=b.x;t.update(.01);assert.equal(a.x,ax);assert.equal(b.x,bx,'Resuming clears both sets of held keys');
t.start();t.clearFish();[a,b]=pair();a.x=b.x=300;a.y=b.y=200;
t.setFish(12);t.update(.001);assert.equal(a.score+b.score,1);assert.equal(t.get().fish.length,0,'Shared fish is removed once even when both players touch it');
t.start();t.clearFish();[a,b]=pair();t.setFish(12);const food=t.get().fish[0];food.x=b.x;food.y=food.baseY=b.y;t.update(.001);assert.equal(a.score,0);assert.equal(b.score,1,'2P can catch and score shared prey');
t.start();t.clearFish();[a,b]=pair();t.placeSpecial(1);const special=t.get().specials[0];special.x=b.x;special.y=special.baseY=b.y;t.update(.001);assert.equal(a.score,0);assert.equal(b.score,32);assert.equal(t.get().specials.length,0,'2P can catch a swimming special creature');
t.start();t.clearFish();[a,b]=pair();t.placePickup('shield');const pickup=t.get().pickups[0];pickup.x=b.x;pickup.y=pickup.baseY=b.y;pickup.phase=0;t.update(.001);assert.equal(b.shieldTime,8);assert.equal(a.shieldTime,0);assert.equal(t.get().pickups.length,0);
t.start();t.clearFish();[a,b]=pair();t.spawn(true,t.get().species.find(s=>s.name==='赤鲨'));const shark=t.get().fish.at(-1);a.x=50;a.y=100;b.x=750;b.y=330;shark.x=620;shark.y=shark.baseY=300;shark.dir=1;const oldY=shark.baseY;t.moveFish(shark,.01);assert.ok(shark.baseY>oldY,'Predators follow 2P at normal swimming speed');
t.start();t.clearFish();[a,b]=pair();t.eat({score:1900,x:0,y:0},a);assert.equal(t.get().state,'playing','One player reaching level ten does not end the other player’s run');
a.x=b.x;a.y=b.y;t.placeSpecial(1);t.update(.001);assert.equal(a.score,1900);assert.equal(b.score,32,'Max-level players leave special growth food for their teammate');
t.eat({score:1900,x:0,y:0},b);assert.equal(t.get().state,'won','Both players reaching level ten wins together');
t.start();t.clearFish();[a,b]=pair();for(let i=0;i<3;i++){b.invulnerable=0;t.hit('shark',false,b);}assert.equal(a.lives,3);assert.equal(b.lives,0);assert.equal(t.get().state,'playing','One player losing all lives leaves the other player running');assert.equal(b.outcome,'over');assert.equal(a.outcome,'playing');for(let i=0;i<3;i++){a.invulnerable=0;t.hit('shark',false,a);}assert.equal(t.get().state,'over','The session ends after both players finish');
press('r');assert.equal(pair().length,2);assert.ok(pair().every(p=>p.score===0&&p.level===0&&p.lives===3&&p.shieldTime===0&&p.dashCooldown===0),'Restart resets both players');
t.clearFish();viewport.width=350;viewport.height=470;t.resize();for(const p of pair()){p.x=-100;p.y=2000;t.confinePlayer(p);assert.ok(p.x>=t.screenRadius(p.r)*1.2&&p.y<470,'Both players fit narrow screens');}
t.eat({score:1900,x:0,y:0},pair()[0]);t.eat({score:1900,x:0,y:0},pair()[1]);t.setMode('solo');t.start();t.clearFish();assert.equal(pair().length,1);ax=pair()[0].x;press('ArrowRight');t.update(.1);release('ArrowRight');assert.ok(pair()[0].x>ax,'Switching back to single player restores arrow controls');
const source=fs.readFileSync('docs/game.js','utf8');assert.equal(source.split('ctx.ellipse(').length-1,1,'Only the shield ring remains');
console.log('PASS: independent two-player controls/growth/effects, simultaneous input, one-time shared catches, 2P pickups and special creatures, predator targeting, independent win/loss, pause/restart, mobile boundaries and solo fallback.');
